import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "./providers";
import { LenguajeProvider } from "./Providers/LenguajeProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <body className={inter.className}>
        <Providers>
          <LenguajeProvider>{children}</LenguajeProvider>
        </Providers>
      </body>
    </html>
  );
}
